/*
* CONSTANT TYPES 
*/

// Preloader
export const SHOW_PRELOADER = 'SHOW_PRELOADER'
export const HIDE_PRELOADER = 'HIDE_PRELOADER'

// Countries
export const SHOW_FOUND_COUNTRIES = 'SHOW_FOUND_COUNTRIES'
export const SHOW_ALL_COUNTRIES = 'SHOW_ALL_COUNTRIES'
export const REQUEST_COUNTRIES = 'REQUEST_COUNTRIES'
export const RECEIVE_COUNTRIES = 'RECEIVE_COUNTRIES'

// Cities
export const REQUEST_CITIES = 'REQUEST_CITIES'
export const RECEIVE_CITIES = 'RECEIVE_CITIES'
export const HIDE_CITIES = 'HIDE_CITIES'

//Login
export const GET_ACCESS = 'GET_ACCESS'
export const CANCEL_ACCESS = 'CANCEL_ACCESS'
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const CANCEL_STATUS = 'CANCEL_STATUS'
export const AVAILABLE_SIGN_UP = 'AVAILABLE_SIGN_UP'
export const UNAVAILABLE_SIGN_UP = 'UNAVAILABLE_SIGN_UP'
export const AVAILABLE_LOGIN = 'AVAILABLE_LOGIN'
export const UNAVAILABLE_LOGIN = 'UNAVAILABLE_LOGIN'