/*
* CONSTANT TYPES 
*/
// Preloader
export const SHOW_PRELOADER = 'SHOW_PRELOADER'
export const HIDE_PRELOADER = 'HIDE_PRELOADER'

// Countries
export const SHOW_FOUND_COUNTRIES = 'SHOW_FOUND_COUNTRIES'
export const SHOW_ALL_COUNTRIES = 'SHOW_ALL_COUNTRIES'
export const REQUEST_COUNTRIES = 'REQUEST_COUNTRIES'
export const SUCCESS_COUNTRIES = 'SUCCESS_COUNTRIES'
export const FAILURE_COUNTRIES = 'FAILURE_COUNTRIES'

// Cities
export const REQUEST_CITIES = 'REQUEST_CITIES'
export const SUCCESS_CITIES = 'SUCCESS_CITIES'
export const FAILURE_CITIES = 'FAILURE_CITIES'
export const HIDE_CITIES = 'HIDE_CITIES'

//Authentication
export const GET_ACCESS = 'GET_ACCESS'
export const CANCEL_ACCESS = 'CANCEL_ACCESS'
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const CANCEL_STATUS = 'CANCEL_STATUS'
export const REQUEST_CREATE_USER_ACCOUNT = 'REQUEST_CREATE_USER_ACCOUNT'
export const SUCCESS_CREATE_USER_ACCOUNT = 'SUCCESS_CREATE_USER_ACCOUNT'
export const REQUEST_SEND_USER_DATA = 'REQUEST_SEND_USER_DATA'
export const SUCCESS_SEND_USER_DATA = 'SUCCESS_SEND_USER_DATA'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

//Fields value length
export const MIN_LENGTH = 'MIN_LENGTH'
//Errors
export const INCORRECT_LOGIN_OR_PASSWORD = 'INCORRECT_LOGIN_OR_PASSWORD'
export const USERNAME_IS_ALREADY_TAKEN = 'USERNAME_IS_ALREADY_TAKEN'
export const ALL_FIELDS_ARE_REQUIRED = 'ALL_FIELDS_ARE_REQUIRED'
export const PASSWORDS_SHOULD_BE_SAME = 'PASSWORDS_SHOULD_BE_SAME'
export const INCORRECT_VALUE_LENGTH = 'INCORRECT_VALUE_LENGTH'

//Success
export const LOGIN_AND_PASSWORD_ARE_CORRECT = 'LOGIN_AND_PASSWORD_ARE_CORRECT'
export const USERNAME_IS_RIGHT = 'USERNAME_IS_RIGHT'
export const ALL_FIELDS_ARE_FILLED = 'ALL_FIELDS_ARE_FILLED'
export const PASSWORDS_ARE_SAME = 'PASSWORDS_ARE_SAME'
export const VALUE_LENGTH_IS_CORRECT = 'VALUE_LENGTH_IS_CORRECT'